version: '2'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
  backend:
    build: ./backend
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      - DOCKERISED=true

  db:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d/:ro
      - ./backend/csv_data:/csv_data
