version: '2'

services:
  frontend:
    build: .
    ports:
      - "8080:8080"
  backend:
    build: ./backend
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      - DOCKERISED=true
    depends_on:
      db:
        condition: service_healthy   
     

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d/:ro
      - ./backend/csv_data:/csv_data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s                  
      retries: 5  
